const express = require("express");
const addToCart = require("../controllers/cart/addToCart");
const deleteFromCart = require("../controllers/cart/deleteFromCart");
const editItemQuantity = require("../controllers/cart/editItemQuantity");
const orderCart = require("../controllers/cart/orderCart");
const seeAllDelivered = require("../controllers/cart/seeAllDelivered");
const seeAllPending = require("../controllers/cart/seeAllPending");
const seeCartItems = require("../controllers/cart/seeCartItems");
const seeCartItemsUser = require("../controllers/cart/seeCartItemsUser");
const seeDeliveredUser = require("../controllers/cart/seeDeliveredUser");
const seePendingUser = require("../controllers/cart/seePendingUser");
const setToDelivered = require("../controllers/cart/setToDelivered");
const setToDelivery = require("../controllers/cart/setToDelivery");
const cartRouter = express.Router();
cartRouter.route("/:itemsize_id").post(addToCart).delete(deleteFromCart);
cartRouter.put("/quantity", editItemQuantity);
cartRouter.post("/order", orderCart);
cartRouter.get("/delivered", seeAllDelivered);
cartRouter.get("/pending", seeAllPending);
cartRouter.get("/items/user", seeCartItemsUser);
cartRouter.get("/items/:cart_id", seeCartItems);
cartRouter.get("/delivered/:user_id", seeDeliveredUser);
cartRouter.get("/pending/:user_id", seePendingUser);
cartRouter.put("/delivery/:cart_id", setToDelivery);
cartRouter.put("/delivered/:cart_id", setToDelivered);
module.exports = cartRouter;
