const express = require("express");
const deleteUser = require("../controllers/user/deleteUser");
const editFname = require("../controllers/user/editFname");
const editLname = require("../controllers/user/editLname");
const editMail = require("../controllers/user/editMail");
const editPass = require("../controllers/user/editPass");
const login = require("../controllers/user/login");
const register = require("../controllers/user/register");
const userRouter = express.Router();
userRouter.post("/register", register);
userRouter.post("/login", login);
userRouter.delete("/:user_id", deleteUser);
userRouter.put("/fname/:user_id", editFname);
userRouter.put("/lname/:user_id", editLname);
userRouter.put("/pass/:user_id", editPass);
userRouter.put("/mail/:user_id", editMail);
module.exports = userRouter;
